package com.rojoma.`json-impl`.dynamic

// This used to be generated by ValueClassSupportBuilder, but then
// Scala 2.10 dashed my hopes of making the DynamicJValue a value
// class wrapper, so in order to preserve binary compatibility with
// 2.8 and 2.9, here it is.
object DynamicJValueSuperClassHolder {
  import com.rojoma.json.dynamic.DynamicJValue
  abstract class SuperClass { this: DynamicJValue =>
    override def hashCode = static.hashCode
    override def equals(x: Any) = x match {
      case that: DynamicJValue => this.static == that.static
      case _ => false
    }
  }
}
